# Generated by Django 3.2.5 on 2023-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_ais_data_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais_data_routes',
            name='Ship_id',
            field=models.CharField(max_length=111),
        ),
    ]
