# Generated by Django 3.2.5 on 2023-02-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_ais_data_routes_ship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais_data_routes',
            name='Latitude',
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name='ais_data_routes',
            name='Logitude',
            field=models.CharField(max_length=111),
        ),
    ]
