# Generated by Django 3.2.5 on 2023-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20230207_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais_data_routes',
            name='id',
            field=models.CharField(max_length=111, primary_key=True, serialize=False),
        ),
    ]
