# Generated by Django 3.2.5 on 2023-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_ais_data_routes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIS_data_report',
            fields=[
                ('id', models.CharField(max_length=111, primary_key=True, serialize=False)),
                ('RANK', models.CharField(max_length=111)),
                ('SHIPPING_COMPANY', models.CharField(max_length=111)),
                ('Num_of_ships', models.CharField(max_length=111)),
                ('CAPACITY', models.CharField(max_length=111)),
                ('URL', models.CharField(max_length=111)),
            ],
        ),
    ]
