# Generated by Django 3.2.5 on 2023-02-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_alter_ais_data_report_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIS_data_updates',
            fields=[
                ('id', models.CharField(max_length=111, primary_key=True, serialize=False)),
                ('mmsi', models.CharField(blank=True, max_length=111, null=True)),
                ('heading', models.CharField(blank=True, max_length=111, null=True)),
                ('shiptype', models.CharField(blank=True, max_length=111, null=True)),
                ('width', models.CharField(blank=True, max_length=111, null=True)),
                ('length', models.CharField(blank=True, max_length=111, null=True)),
            ],
        ),
    ]
